### ISSUE TITLE
Merge?

### ISSUE THREAD

**Issue by JohnLangford** [mwydmuch/extweme_wabbit#1]
Is it interesting to merge this into the VW master branch?

**Comment by mwydmuch** [comment]
Hello @JohnLangford, this fork implements quite straightforward version of Probabilistic Label Tree, but I think it can be a useful alternative to multilabel OAA. I will gladly sync it with the master, document and prepare a merge request.

**Comment by eisber** [comment]
@mwydmuch mind merging my PR before going upstream?

**Comment by JohnLangford** [comment]
Looking forward to merging into master.

**Comment by mwydmuch** [comment]
It took a while, but PLT was just merged to master, thank you @JohnLangford for proposing it, I'm very excited that I was able to contribute to VW. And thank you @eisber, for improving the implementation!

**Comment by JohnLangford** [comment]
Great, thank you :-)

-John
